name: Deploy React App
on:
  push:
    branches:
      - main
      - feature/**
      - "!feature/authen"
  workflow_dispatch:
  pull_request:
    types:
      - opened

env:
  BUN_VERSION: latest

jobs:
  build:
    environment: test
    runs-on: ubuntu-latest
    container:
      image: oven/bun:1
      env:
        NODE_ENV: production
    steps:
      - name: Print Bun version
        run: echo "Bun version ${{ vars.BUN_VERSION }}"
      - name: Print API KEY
        run: echo "API KEY ${{ secrets.API_KEY }}"
      - name: Clone repository
        uses: actions/checkout@v5
      # - name: Setup bun
      #   uses: oven-sh/setup-bun@v2
      #   with:
      #     bun-version: ${{ vars.BUN_VERSION }}
      - name: Caching
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
      - name: Install dependencies
        run: bun i
      - name: Build
        run: bun run build
      - name: List dist/
        run: ls dist
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist/

  deploy:
    if: success()
    runs-on: ubuntu-latest
    needs: 
      - build
    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist-folder
          path: dist
      - name: Deploy
        run: echo "Deploying..."
      # - name: Force failed
      #   run: exit 1

  notify-failed:
    runs-on: ubuntu-latest
    needs:
      - build
      - deploy
    if: failure() # failure() | cancelled() | always() | success()
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1421697869458706533/W2UqZa7gD95EU7ixa4gQN3QLz3pWc3oFepvpv16XWxfpuMMTTiqbNULZWrBBmPfPlYBY
        uses: Ilshidur/action-discord@master
        with:
          args: "# ðŸš¨ Build Commit ${{ github.sha }} | Crafted by Nat49"

  notify-success:
    runs-on: ubuntu-latest
    needs:
      - build
      - deploy
    if: success() # failure() | cancelled() | always() | success()
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1421697869458706533/W2UqZa7gD95EU7ixa4gQN3QLz3pWc3oFepvpv16XWxfpuMMTTiqbNULZWrBBmPfPlYBY
        uses: Ilshidur/action-discord@master
        with:
          args: "# ðŸš€ Build Commit ${{ github.sha }} | Crafted by Nat49"
